disableKinds = ['home', 'taxonomy', 'term']
enableRobotsTXT = true
languageCode = "en-us"
title = "Multiformats"

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "A collection of protocols for future-proofing systems, today."
  specifications = "https://github.com/multiformats/specs"
  
  author = "Protocol Labs"
  github = "https://github.com/multiformats/multiformats"
  name = "Multiformats"